services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - REDIS_HOST=redis-db
      - REDIS_PORT=6379
      - LOCAL=true
    
    depends_on:
      - redis-db 
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  redis-db:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  redisdata: