
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:

    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend