services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:3001/api
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOCAL=true
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data
    environment:
      - RI_REDIS_HOST_LOCAL=redis
      - RI_REDIS_PORT_LOCAL=6379
      - RI_REDIS_HOST_PROD=redis
      - RI_REDIS_PORT_PROD=6379
    depends_on:
      - redis

volumes:
  redisdata:
  redisinsight_data:
