name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies for backend
        working-directory: ./backend
        run: npm install

      - name: Run tests for frontend
        working-directory: ./backend
        run: npm run test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    # Only run this step if the branch is main
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy Backend
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL_BACKEND }}
        run: |
          curl "$deploy_url"

      - name: Deploy Frontend
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL_FRONTEND }}
        run: |
          curl "$deploy_url"
