name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias (backend)
        working-directory: ./backend
        run: npm install

      - name: Ejecutar tests (backend)
        working-directory: ./backend
        run: npm run test


  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Backend
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL_BACKEND }}
        run: |
          curl "$deploy_url"
      
      - name: Deploy Frontend
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL_FRONTEND }}
        run: |
          curl "$deploy_url"
